### ISSUE TITLE
開発環境構築

### ISSUE THREAD

**Issue by chaikemewtwo** [chaikemewtwo/Aim-for-the-star#1]
ゲームを作成するための開発環境を整える

- [x] VisualStudio2017を使用しプロジェクトを作成する

- [x] DirectX9のパス指定を行う

**Comment by yttmwork** [comment]
せっかくの環境構築なので、directxのパス指定なども合わせてしておきましょう

**Comment by chaikemewtwo** [comment]
ありがとうございます
やってみます
